// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: api/RotatorService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannerID string `protobuf:"bytes,1,opt,name=BannerID,proto3" json:"BannerID,omitempty"`
	SlotID   string `protobuf:"bytes,2,opt,name=SlotID,proto3" json:"SlotID,omitempty"`
}

func (x *AddBannerRequest) Reset() {
	*x = AddBannerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RotatorService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBannerRequest) ProtoMessage() {}

func (x *AddBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_RotatorService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBannerRequest.ProtoReflect.Descriptor instead.
func (*AddBannerRequest) Descriptor() ([]byte, []int) {
	return file_api_RotatorService_proto_rawDescGZIP(), []int{0}
}

func (x *AddBannerRequest) GetBannerID() string {
	if x != nil {
		return x.BannerID
	}
	return ""
}

func (x *AddBannerRequest) GetSlotID() string {
	if x != nil {
		return x.SlotID
	}
	return ""
}

type AddBannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddBannerResponse) Reset() {
	*x = AddBannerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RotatorService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBannerResponse) ProtoMessage() {}

func (x *AddBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_RotatorService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBannerResponse.ProtoReflect.Descriptor instead.
func (*AddBannerResponse) Descriptor() ([]byte, []int) {
	return file_api_RotatorService_proto_rawDescGZIP(), []int{1}
}

type RemoveBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotID   string `protobuf:"bytes,1,opt,name=SlotID,proto3" json:"SlotID,omitempty"`
	BannerID string `protobuf:"bytes,2,opt,name=BannerID,proto3" json:"BannerID,omitempty"`
}

func (x *RemoveBannerRequest) Reset() {
	*x = RemoveBannerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RotatorService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBannerRequest) ProtoMessage() {}

func (x *RemoveBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_RotatorService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBannerRequest.ProtoReflect.Descriptor instead.
func (*RemoveBannerRequest) Descriptor() ([]byte, []int) {
	return file_api_RotatorService_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveBannerRequest) GetSlotID() string {
	if x != nil {
		return x.SlotID
	}
	return ""
}

func (x *RemoveBannerRequest) GetBannerID() string {
	if x != nil {
		return x.BannerID
	}
	return ""
}

type RemoveBannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveBannerResponse) Reset() {
	*x = RemoveBannerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RotatorService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBannerResponse) ProtoMessage() {}

func (x *RemoveBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_RotatorService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBannerResponse.ProtoReflect.Descriptor instead.
func (*RemoveBannerResponse) Descriptor() ([]byte, []int) {
	return file_api_RotatorService_proto_rawDescGZIP(), []int{3}
}

type ClickBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotID   string `protobuf:"bytes,1,opt,name=SlotID,proto3" json:"SlotID,omitempty"`
	BannerID string `protobuf:"bytes,2,opt,name=BannerID,proto3" json:"BannerID,omitempty"`
	GroupID  string `protobuf:"bytes,3,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
}

func (x *ClickBannerRequest) Reset() {
	*x = ClickBannerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RotatorService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickBannerRequest) ProtoMessage() {}

func (x *ClickBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_RotatorService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickBannerRequest.ProtoReflect.Descriptor instead.
func (*ClickBannerRequest) Descriptor() ([]byte, []int) {
	return file_api_RotatorService_proto_rawDescGZIP(), []int{4}
}

func (x *ClickBannerRequest) GetSlotID() string {
	if x != nil {
		return x.SlotID
	}
	return ""
}

func (x *ClickBannerRequest) GetBannerID() string {
	if x != nil {
		return x.BannerID
	}
	return ""
}

func (x *ClickBannerRequest) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

type ClickBannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClickBannerResponse) Reset() {
	*x = ClickBannerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RotatorService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickBannerResponse) ProtoMessage() {}

func (x *ClickBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_RotatorService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickBannerResponse.ProtoReflect.Descriptor instead.
func (*ClickBannerResponse) Descriptor() ([]byte, []int) {
	return file_api_RotatorService_proto_rawDescGZIP(), []int{5}
}

type ChooseBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotID  string `protobuf:"bytes,1,opt,name=SlotID,proto3" json:"SlotID,omitempty"`
	GroupID string `protobuf:"bytes,2,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
}

func (x *ChooseBannerRequest) Reset() {
	*x = ChooseBannerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RotatorService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChooseBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseBannerRequest) ProtoMessage() {}

func (x *ChooseBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_RotatorService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseBannerRequest.ProtoReflect.Descriptor instead.
func (*ChooseBannerRequest) Descriptor() ([]byte, []int) {
	return file_api_RotatorService_proto_rawDescGZIP(), []int{6}
}

func (x *ChooseBannerRequest) GetSlotID() string {
	if x != nil {
		return x.SlotID
	}
	return ""
}

func (x *ChooseBannerRequest) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

type ChooseBannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannerID string `protobuf:"bytes,1,opt,name=BannerID,proto3" json:"BannerID,omitempty"`
}

func (x *ChooseBannerResponse) Reset() {
	*x = ChooseBannerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_RotatorService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChooseBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseBannerResponse) ProtoMessage() {}

func (x *ChooseBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_RotatorService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseBannerResponse.ProtoReflect.Descriptor instead.
func (*ChooseBannerResponse) Descriptor() ([]byte, []int) {
	return file_api_RotatorService_proto_rawDescGZIP(), []int{7}
}

func (x *ChooseBannerResponse) GetBannerID() string {
	if x != nil {
		return x.BannerID
	}
	return ""
}

var File_api_RotatorService_proto protoreflect.FileDescriptor

var file_api_RotatorService_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x6f, 0x74, 0x61,
	0x74, 0x6f, 0x72, 0x22, 0x46, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x22, 0x13, 0x0a, 0x11, 0x41,
	0x64, 0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x49, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6c, 0x6f, 0x74, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x22, 0x16, 0x0a, 0x14, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x62, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6c, 0x6f,
	0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6c, 0x6f, 0x74, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x6c, 0x69, 0x63, 0x6b,
	0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x47,
	0x0a, 0x13, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x22, 0x32, 0x0a, 0x14, 0x43, 0x68, 0x6f, 0x6f, 0x73,
	0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x32, 0xb9, 0x02, 0x0a, 0x07,
	0x52, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x44, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x41,
	0x64, 0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x42, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a,
	0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x1c, 0x2e,
	0x72, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x72, 0x6f,
	0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0b,
	0x43, 0x6c, 0x69, 0x63, 0x6b, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x72, 0x6f,
	0x74, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x43, 0x68, 0x6f, 0x6f,
	0x73, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_RotatorService_proto_rawDescOnce sync.Once
	file_api_RotatorService_proto_rawDescData = file_api_RotatorService_proto_rawDesc
)

func file_api_RotatorService_proto_rawDescGZIP() []byte {
	file_api_RotatorService_proto_rawDescOnce.Do(func() {
		file_api_RotatorService_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_RotatorService_proto_rawDescData)
	})
	return file_api_RotatorService_proto_rawDescData
}

var file_api_RotatorService_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_RotatorService_proto_goTypes = []interface{}{
	(*AddBannerRequest)(nil),     // 0: rotator.AddBannerRequest
	(*AddBannerResponse)(nil),    // 1: rotator.AddBannerResponse
	(*RemoveBannerRequest)(nil),  // 2: rotator.RemoveBannerRequest
	(*RemoveBannerResponse)(nil), // 3: rotator.RemoveBannerResponse
	(*ClickBannerRequest)(nil),   // 4: rotator.ClickBannerRequest
	(*ClickBannerResponse)(nil),  // 5: rotator.ClickBannerResponse
	(*ChooseBannerRequest)(nil),  // 6: rotator.ChooseBannerRequest
	(*ChooseBannerResponse)(nil), // 7: rotator.ChooseBannerResponse
}
var file_api_RotatorService_proto_depIdxs = []int32{
	0, // 0: rotator.Rotator.AddBanner:input_type -> rotator.AddBannerRequest
	2, // 1: rotator.Rotator.RemoveBanner:input_type -> rotator.RemoveBannerRequest
	4, // 2: rotator.Rotator.ClickBanner:input_type -> rotator.ClickBannerRequest
	6, // 3: rotator.Rotator.ChooseBanner:input_type -> rotator.ChooseBannerRequest
	1, // 4: rotator.Rotator.AddBanner:output_type -> rotator.AddBannerResponse
	3, // 5: rotator.Rotator.RemoveBanner:output_type -> rotator.RemoveBannerResponse
	5, // 6: rotator.Rotator.ClickBanner:output_type -> rotator.ClickBannerResponse
	7, // 7: rotator.Rotator.ChooseBanner:output_type -> rotator.ChooseBannerResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_RotatorService_proto_init() }
func file_api_RotatorService_proto_init() {
	if File_api_RotatorService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_RotatorService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBannerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RotatorService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBannerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RotatorService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveBannerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RotatorService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveBannerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RotatorService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickBannerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RotatorService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickBannerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RotatorService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChooseBannerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_RotatorService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChooseBannerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_RotatorService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_RotatorService_proto_goTypes,
		DependencyIndexes: file_api_RotatorService_proto_depIdxs,
		MessageInfos:      file_api_RotatorService_proto_msgTypes,
	}.Build()
	File_api_RotatorService_proto = out.File
	file_api_RotatorService_proto_rawDesc = nil
	file_api_RotatorService_proto_goTypes = nil
	file_api_RotatorService_proto_depIdxs = nil
}
