name: Banner rotation tests

on:
  push:
    branches:
      - develop

env:
  GO111MODULE: "on"

jobs:
  tests_by_makefile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out code
        uses: actions/checkout@v2

      - name: lint
        run: make lint

      - name: build
        run: make build

      - name: test
        run: make test

      - name: integration-tests
        run: make integration-tests